### ISSUE TITLE
Attributes

### ISSUE THREAD

**Issue by arielcedola** [MicrosoftDocs/MachineLearning-Python-Feedback#13]
Hi, maybe for the sake of completion would be nice also adding the attributes of model class, right? For example name, version, etc. They are in fact being used in some sample notebooks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08d33267-fb2b-bc8a-1b61-50122b944dd1
* Version Independent ID: 17c92047-89c8-0881-6d9f-235f50a2d5af
* Content: [azureml.core.model.Model class](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.model.model?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.model.Model.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.model.Model.yml)
* Service: **azure**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by j-martens** [comment]
Thank you for your post. We will take it under advisement and share with the development team.
