### ISSUE TITLE
Does onnxruntime support more than two inputs?

### ISSUE THREAD

**Issue by riacheruvu** [MicrosoftDocs/MachineLearning-Python-Feedback#22]
When implementing sess.run with onnxruntime after creating an Inference Session, is it possible to feed in two inputs? For example,

pred_onx = sess.run([label_name], {input_name: x, second_input_name: x})[0]

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72cff31a-2cbc-412c-5393-953d9325d7e4
* Version Independent ID: 297a8475-e718-90e6-c33e-179535debf88
* Content: [Load and predict with ONNX Runtime and a very simple model](https://docs.microsoft.com/en-us/python/api/overview/azure/onnx/auto-examples-plot-load-and-predict?view=azure-onnx-py)
* Content Source: [onnx-runtime/docs-ref-conceptual/auto-examples-plot-load-and-predict.md](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/onnx-runtime/docs-ref-conceptual/auto-examples-plot-load-and-predict.md)
* Service: **azure**
* GitHub Login: @Microsoft
* Microsoft Alias: **faxu**

**Comment by AleksCallebat** [comment]
Hello Ria,
Do you mean two inputs/data points that needs to go sequentially through the model in order to get the two results? x is a sequence of inputs, so you just need to feed { input_name : np.array([x for x in youdata],dtype=numpy.float32)) }

Hope it answers :)

**Comment by riacheruvu** [comment]
Thank you for the response, @AleksCallebat! I tried using the code you provided, and still receive the error "Model requires 2 inputs. Input Feed contains 1". To clarify on my question, the model I would like to run with onnxruntime takes two inputs (both of which are int64[1, 1]) and has one output (float32[1,1]).

Thank you!

**Comment by athene1021** [comment]
I think you can use:

  input_feeds = {}
  for i in range(inputs_num):
      input_feeds[sess.get_inputs()[i].name] = inputs[i]

  outputs = list(sess.run([label_name], input_feeds))

**Comment by riacheruvu** [comment]
Thank you for the reply, @athene1021! I will try this solution the next time I use onnxruntime for this use case; I'll close the issue for now.

**Comment by CosmicHunter** [comment]
@athene1021   I tried your solution to pass multiple inputs to the onnx runtime but I am getting errors , my model is an lstm model for sentiment classification . The code is like this.

~~~
dummyh = torch.ones(2,1,256)  // for hidden state and cell state of lstm
# feature_tensor is of dimension 1,200 . 
input_feeds = {}
ris = [feature_tensor , dummyh , dummyh]
for i in range(3):
  input_feeds[runtime_session.get_inputs()[i].name] = ris[i]
pred = list(runtime_session.run([output_name],input_feeds)
~~~
#### RuntimeError: Input must be a list of dictionaries or a single numpy array for input '1'.

Can you please suggest a solution on how to pass multiple inputs @riacheruvu ?
Thank you

**Comment by riacheruvu** [comment]
@CosmicHunter, I’m sorry, I didn’t have the chance to look into this issue further, so I can’t suggest a solution. I hope you can find the solution to your issue.

**Comment by CosmicHunter** [comment]
Thanks , I found out the solution and the inputs need to be passed as a dictionary.
~~~
pred = runtime_session.run([output_name],{runtime_session.get_inputs()[0].name:to_numpy(input1).astype(np.longlong),
                                                                   runtime_session.get_inputs()[1].name:to_numpy(input2),
                                                                   runtime_session.get_inputs()[2].name:to_numpy(input3)})
~~~
