### ISSUE TITLE
What is Azure Machine Learning?

### ISSUE THREAD

**Issue by DaveVoyles** [MicrosoftDocs/MachineLearning-Python-Feedback#3]
At the top of the post, where it says this is deprecated now, it reads:
"It cannot be used with the latest version of Azure Machine Learning."

Does that mean ML Workbench? Studio? Or something else?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f18be8ab-d716-9150-e2e8-cb037b777568
* Version Independent ID: fb16f652-7ef8-72a1-5ecd-e206ea0a2292
* Content: [Azure Machine Learning Package for Forecasting](https://docs.microsoft.com/en-us/python/api/overview/azure/forecasting/intro?view=azure-forecasting-py)
* Content Source: [Forecasting/docs-ref-conceptual/intro.md](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/Forecasting/docs-ref-conceptual/intro.md)
* Service: **machine-learning**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by j-martens** [comment]
If you are satisfied, #please-close.
