### ISSUE TITLE
Blob storage Emulator

### ISSUE THREAD

**Issue by matallanas** [MicrosoftDocs/MachineLearning-Python-Feedback#31]
I have an issue using the dataprep library with a local blob storage emulator.
If I wanted to use dataprep within a blob storage emulator such us Azurite, dataprep is not compatible with local blob storage emulator uris. My guess is because 

- An URI from an azure blob storage is of the form: `<http|https>://<account-name>.blob.core.windows.net/<resource-path>`

- An URI from local blob storage emulator: `http://<local-machine-address>:<port>/<account-name>/<resource-path>`

There must be something that is not assigning correctly the FileDataSource.
Is there anything that can be done to use this local blob storage emulators?

Thank you very much.

**Comment by yikei** [comment]
Hi @matallanas , could you share your code snippet? Are you passing in the URI from the emulator into `read_csv()`?

Could you try creating a [`dataprep.BlobDataSource`](https://docs.microsoft.com/en-us/python/api/azureml-dataprep/azureml.dataprep.blobdatasource?view=azure-ml-py), and then passing that to `read_csv()`?

Thanks,
Monica

**Comment by matallanas** [comment]
Hi @yikei , so I was using the following SAS token blob storage path:
`  path_azurite = "http://127.0.0.1:10000/devstoreaccount1/landing/example.csv?st=2019-07-04T08%3A31%3A37Z&se=2019-07-05T08%3A31%3A37Z&sp=rl&sv=2018-03-28&sr=b&sig=GUzFphP8S704H4k4Gn%2Fh2GbchFEeuCDhtiiQnCi6eQI%3D"
`

When I tried to open this path directly I obtain the following error
![image](https://user-images.githubusercontent.com/6162841/60654220-7a198100-9e43-11e9-8179-00f3aa1d1ce4.png)

So I follow the problem and see that the URL was treated as a FileDataSource rather than a blobDataSource:
`
DataSourcePropertyValue({
  "resourceDetails": [
    {
      "path": "/mnt/e/http:/127.0.0.1:10000/devstoreaccount1/landing/example.csv?st=2019-07-04T08%3A31%3A37Z&se=2019-07-05T08%3A31%3A37Z&sp=rl&sv=2018-03-28&sr=b&sig=GUzFphP8S704H4k4Gn%2Fh2GbchFEeuCDhtiiQnCi6eQI%3D"
    }
  ],
  "target": 0
})
`

The I tried your solution:
`dataprep.read_csv(path=dataprep.BlobDataSource(path_azurite), separator=',')

And everything is working now. 
Thank you very much for your help, it was awesome.
Cheers,
Edu

**Comment by yikei** [comment]
That's great to hear, thanks for the update!
