### ISSUE TITLE
Duplicate Remarks

### ISSUE THREAD

**Issue by tarockey** [MicrosoftDocs/MachineLearning-Python-Feedback#6]
The remarks for most of these methods and attributes are the same remarks at the top of the page (the definition).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47d45e80-f383-aeab-3c36-78db3481325a
* Version Independent ID: 49573b7e-1193-c0d0-b2a1-c38eaaed943c
* Content: [azureml.core.Experiment class](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.experiment(class)?view=azure-ml-py#get-docs-url)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.Experiment(class).yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.Experiment(class).yml)
* Service: **azure**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by j-martens** [comment]
Thank you for your post. We will take it under advisement and share with the development team.

**Comment by j-martens** [comment]
Fixed.
