### ISSUE TITLE
Join method - example

### ISSUE THREAD

**Issue by ArvidBaa** [MicrosoftDocs/MachineLearning-Python-Feedback#7]
Is it possible to add an example on how to do a join between two Dataflows? Should the method be called from the Dataprep class (`dprep.join()`), or on one of the Dataflows (`dataflow.join()`)? Where do I provide reference two the Dataflow(s) that should be joined? I can only see that the method takes in the columns as parameters, not the actual Dataflow(s). Should I specify which column to join by, or is it inferred as the column not being prefixed?

Or is this simply a preparation method, that simply prepares the Dataflows for a join, that is executed by a completely separate method? If so, which method is that?

Thanks in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd2c81e8-16b6-259f-d652-aa70839ff107
* Version Independent ID: 7bfe2e7f-7931-0e0b-4e32-ee72ce41f297
* Content: [azureml.dataprep.api.dataflow.Dataflow class](https://docs.microsoft.com/en-us/python/api/azureml-dataprep/azureml.dataprep.api.dataflow.dataflow?view=azure-dataprep-py#join)
* Content Source: [DataPrep/docs-ref-autogen/azureml-dataprep/azureml.dataprep.api.dataflow.Dataflow.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/DataPrep/docs-ref-autogen/azureml-dataprep/azureml.dataprep.api.dataflow.Dataflow.yml)
* Service: **azure**
* GitHub Login: @dsindona
* Microsoft Alias: **Dana.Sindona**

**Comment by dsindona** [comment]
@cforbe

**Comment by cforbe** [comment]
Hi @ArvidBaa 

There are three ways one can join two dataflows in DataPrep:
1. Create JoinBuilder object for interactive join configuration.
2. Call join() on one of the dataflows and pass in the other along with all other arguments.
3. Call Dataflow.join() method and pass in two dataflows along with all other arguments.

Here's more information about join:
https://github.com/Microsoft/PendletonDocs/blob/master/API/join.ipynb

**Comment by j-martens** [comment]
Thank you for your post. We will proceed to close now.
