### ISSUE TITLE
`get_model_path()` is deprecated?

### ISSUE THREAD

**Issue by ArvidBaa** [MicrosoftDocs/MachineLearning-Python-Feedback#8]
When I try using `get_model_path()` I get warning saying `Deprecated, use Run.get_context() instead`. Is this correct, and should the document be updated accordingly? I am using Azure Machine Learning SDK version 0.1.65.

I am also wondering why the method has `model_name` as parameter. Since the method is called from a model object, isn't the model name already known?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08d33267-fb2b-bc8a-1b61-50122b944dd1
* Version Independent ID: 17c92047-89c8-0881-6d9f-235f50a2d5af
* Content: [azureml.core.model.Model class](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.model.model?view=azure-ml-py#get-model-path)
* Content Source: [AzureML/docs-ref-autogen/azureml-core/azureml.core.model.Model.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-core/azureml.core.model.Model.yml)
* Service: **azure**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by akshaya-a** [comment]
Thanks for the reports @ArvidBaa!

1. The warning is a bug we've fixed in the upcoming release - there is no change needed on your side (get_model_path internally uses a deprecated function)
2. get_model_path is a static function. It does indeed look like a documentation bug however, we'll sort that out

**Comment by ArvidBaa** [comment]
Ah, thank you!

**Comment by j-martens** [comment]
@akshaya-a - is the doc fix expected soon so we can close this issue?
